Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.host = 'localhost'
    libvirt.uri = 'qemu:///system'
  end
config.vm.define "new" do |devenv|
  devenv.vm.box = "devenv"
    devenv.vm.provider :libvirt do |test|
      test.memory = 2048
      test.cpus = 2
    end
  end
end
